# example compose up with .env file: 
# docker compose --env-file ./.env up --build

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8333:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 100s
      timeout: 5s
      retries: 3
    # volumes:
    #   - .:/app
    volumes:
      - type: bind
        source: ./
        target: /app
        is_directory: true   # Instructs Coolify to create the directory.
    working_dir: /app
    command: php -S 0.0.0.0:8000
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY:-appTestKey!}
      - APP_DEBUG=true
      - APP_NAME=${APP_NAME:-Laravel}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}