services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8333:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 100s
      timeout: 5s
      retries: 3
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000